### ISSUE TITLE
Port the library to C#

### ISSUE THREAD

**Issue by AhmedKamal** [fikr4n/itl-java#1]
Hi , I would like to port your library to C# so it becomes accessible to more platforms like Windows Phone , Windows 8.1 , Xamarin , ... etc

I would like to have a chat with you if possible before starting this port. Thanks a lot.

**Comment by fikr4n** [comment]
I am sorry, I just remembered to reply. Originally this is not mine, it's from libitl as I wrote in the readme. It's GPL licensed, so everyone is free to port/modify as long as it remains "free". 

So what can I help you about? But don't ask me about the algorithm, I am not finished studying the calculation method yet :D.
