### ISSUE TITLE
Get the Prayer End time

### ISSUE THREAD

**Issue by fahimsakri-zz** [fikr4n/itl-java#2]
Is there a way to findout the prayer end time?

**Comment by fikr4n** [comment]
Prayer end time is before the next prayer, except fajr which ends at
sunrise (shorooq). Special notes on isha, the are some (scientific)
opinions, e.g. isha ends at midnight, 2/3 night, or 1/3 night normally, but
extended until before the next prayer (fajr) at emergency condition.

**Comment by fikr4n** [comment]
Actually there are also some (scientific) opinions (based on Qur'an and
Hadith) about the end of each prayer time, some of them is stronger (more
sahih/rajih) than the others. And there is also the term "normal condition"
and "emergency condition" for other prayers, not only for the end of isha
time. To make it simple, it can be said that the end of a prayer time is
the starting of the next prayer, except for fajr which ends just before the
sunrise.
