### ISSUE TITLE
DayLightSaving problem

### ISSUE THREAD

**Issue by muradmohdzain** [fikr4n/itl-java#3]
Hello,

I'm using this library in my android app and it was totally awesome!. But some country I got problem with the DST

Country : Morocco
City : Marrakech
Lat/Lng : 31.63, -8.008889
TimeZone : Africa/Casablanca 

boolean inDayLight = timeZone.inDaylightTime(new Date());

inDayLight returns TRUE

daylightOffset = timeZone.getDSTSavings() / (60_60_1000); // return 1

org.arabeyes.itl.prayer.astro.Location location = new org.arabeyes.itl.prayer.astro.Location(loc.getLatitude(), loc.getLongitude(), Integer.parseInt(gmtdst[0]), daylightOffset);

PrayerTimeCalc calculator = new PrayerTimeCalc(location, Method.MUSLIM_LEAGUE);

Expected output : Fajr 5.57
Actual output     : Fajr 6.57

Try to subtract -1 for DST but output subtracted 2 hours.

daylightOffset = -1
Expected output : Fajr 5.57
Actual output      : Fajr 4.57

Please help me.

**Comment by fikr4n** [comment]
I am sorry, unintentionally close the issue..

**Comment by fikr4n** [comment]
I am sorry, I forgot to inspect this problem. Btw have you find the solution? 

You can also check my other project at https://github.com/fikr4n/iclib-java.

**Comment by fikr4n** [comment]
I test with this code:

```java
        TimeZone tz = TimeZone.getTimeZone("Africa/Casablanca");
        GregorianCalendar calendar = new GregorianCalendar(tz);
        calendar.set(2016, Calendar.JULY, 11, 0, 0, 0);

        Location location = new Location(31.63, -8.008889,
                calendar.get(Calendar.ZONE_OFFSET) / (3600 * 1000),
                calendar.get(Calendar.DST_OFFSET) / (3600 * 1000));
        PrayerTimeCalc calculator = new PrayerTimeCalc(location, Method.MUSLIM_LEAGUE);
        PrayerTimes times = calculator.getPrayerTimes(calendar.getTime());
        System.out.println("Fajr: " + times.get(PrayerTimes.FAJR));
```

It prints `Fajr: 4:58:00`. I search in the internet and found that it differs only -10 minutes to 10 minutes with other calculation instead of 1 hour. So, isn't this the correct time?

As for 10-Jul-2016 I got "3:57:00". While in the internet some of them differs in DST on 9-Jul-2016 and some of them shows no difference in DST even on 1-Jul-2016.
